#!/usr/bin/with-contenv bash

# env check
if [[ -z "${SMA_PATH}" ]]; then
  export SMA_PATH="/usr/local/sma"
fi

if [[ -z "${SMA_PATH}" ]]; then
  export SMA_FFMPEG_URL="https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
fi

apt-get -qq update >/dev/null
apt-get install -yqq \
  wget \
  python3 \
  python3-pip \
  git >/dev/null
python3 -m pip install --user --upgrade pip >/dev/null
python3 -m pip install --user virtualenv >/dev/null
python3 -m virtualenv ${SMA_PATH}/venv >/dev/null
${SMA_PATH}/venv/bin/pip install -yqq -r ${SMA_PATH}/setup/requirements.txt >/dev/null

# update from git
if [[ "${SMA_UPDATE}" == "true" ]]
then
    git -C ${SMA_PATH} pull origin master --quiet
fi

# ffmpeg
if [[ -f "/usr/local/bin/ffmpeg" ]]
then
    :
else
    wget -q ${SMA_FFMPEG_URL} -O /tmp/ffmpeg.tar.xz
    tar -xJf /tmp/ffmpeg.tar.xz -C /usr/local/bin --strip-components 1
    chown abc:abc /usr/local/bin/ffmpeg
    chown abc:abc /usr/local/bin/ffprobe
    chmod g+x /usr/local/bin/ffmpeg
    chmod g+x /usr/local/bin/ffprobe
    rm -rf /tmp/*
fi

# permissions
chown -R abc:abc ${SMA_PATH}
chmod -R 775 ${SMA_PATH}/*.sh

# update autoprocess
${SMA_PATH}/venv/bin/python3 ${SMA_PATH}/update.py

exit $?
